### ISSUE TITLE
Error list index out of range

### ISSUE THREAD

**Issue by shinjinighosh** [udaya2899/covid-india-api#5]
On running `app.py`, we get the following Stack Trace:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
IndexError: list index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 82, in data_extract
    state_wise_data = html_to_json(table, datetime.now())
  File "app.py", line 68, in html_to_json
    total_items[headers[index]] = total[index-1].text
IndexError: list index out of range
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by shinjinighosh** [comment]
It works now -- thanks!
